# Generated by Django 2.2.4 on 2019-10-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
