# Generated by Django 2.2.4 on 2019-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191027_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttransaction',
            name='desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='newnotification',
            name='desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='oldnotification',
            name='desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='Desc',
            field=models.CharField(max_length=400),
        ),
    ]
