# Generated by Django 2.2.6 on 2019-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_newnotification_oldnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='app1/profile_pics'),
        ),
    ]
