# Generated by Django 2.2.5 on 2019-10-24 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20191023_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField()),
                ('amount', models.IntegerField()),
                ('lent', models.CharField(max_length=20)),
                ('borrowed', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currenttransaction_related1', to=settings.AUTH_USER_MODEL)),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currenttransaction_related2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_related1', to=settings.AUTH_USER_MODEL)),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_related2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id1', 'user_id2')},
            },
        ),
    ]
