# Generated by Django 2.2.5 on 2019-10-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_currenttransaction_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='name',
        ),
    ]
