# Generated by Django 2.2.5 on 2019-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_userprofileinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default='DefaultName', max_length=20),
        ),
    ]
