# Generated by Django 2.2.5 on 2019-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userprofileinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttransaction',
            name='tdate',
            field=models.DateTimeField(),
        ),
    ]
