# Generated by Django 2.2.5 on 2019-10-26 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_auto_20191025_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttransaction',
            name='borrowed',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='currenttransaction',
            name='lent',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Amount', models.IntegerField()),
                ('lent', models.CharField(max_length=30)),
                ('borrowed', models.CharField(max_length=30)),
                ('Desc', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
